pyuic6 creator/mainwindow.ui -o MainWindow.py
pyuic6 creator/2d_flip.ui -o widgets/2d_flip.py
pyuic6 creator/3d_motion.ui -o widgets/3d_motion.py
pyuic6 creator/animation.ui -o widgets/animation.py
pyuic6 creator/depth_warping.ui -o widgets/depth_warping.py
pyuic6 creator/init_image.ui -o widgets/init_image.py
pyuic6 creator/mask.ui -o widgets/mask.py
pyuic6 creator/output.ui -o widgets/output.py
pyuic6 creator/sampler.ui -o widgets/sampler.py
pyuic6 creator/sizer_count.ui -o widgets/sizer_count.py
pyuic6 creator/uploader.ui -o widgets/uploader.py
pyuic6 creator/upscale.ui -o widgets/upscale.py
